services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: sndb
      POSTGRES_USER: snuser
      POSTGRES_PASSWORD: tesT123s4n
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U snuser -d sndb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # broker port
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    build:
      context: ./sn-keycloak-rabbitmq-provider
      dockerfile: Dockerfile
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/sndb
      KC_DB_USERNAME: snuser
      KC_DB_PASSWORD: tesT123s4n
      KC_DB_SCHEMA: keycloak
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
    command:
      - "start-dev"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/realms/master" ]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 5s

  sn-user:
    build:
      context: sn-user # Refers to the directory containing your Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "5005:5005" #debug port
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sndb
      SPRING_DATASOURCE_USERNAME: snuser
      SPRING_DATASOURCE_PASSWORD: tesT123s4n
      JAVA_TOOL_OPTIONS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - backend


volumes:
  postgres_data:
  rabbitmq_data:

networks:
  backend:
    driver: bridge