apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_DB: postgres
  KC_DB_SCHEMA: keycloak
  KC_DB_URL: jdbc:postgresql://postgres:5432/sndb

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"

  KC_HEALTH_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_SCHEMA_CREATE: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: create-keycloak-schema
          image: postgres:16
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -U $POSTGRES_USER; do
                echo "Очікування PostgreSQL..."
                sleep 2
              done
              echo "PostgreSQL готовий. Створюємо схему keycloak..."
              PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d sndb -c "CREATE SCHEMA IF NOT EXISTS keycloak;"
              echo "Схема keycloak створена!"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
      containers:
        - name: keycloak
          image: sn-keycloak:latest # 👈 Образ, який ми зберемо локально
          imagePullPolicy: IfNotPresent # 👈 Не шукати в інтернеті
          args: ["start-dev"]
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-secret
          env:
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080