apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp
  template:
    metadata:
      labels:
        app: smtp
    spec:
      containers:
        - name: smtp
          image: mailhog/mailhog:latest
          ports:
            - containerPort: 1025  # SMTP порт
            - containerPort: 8025  # Web UI порт
---
apiVersion: v1
kind: Service
metadata:
  name: smtp
spec:
  selector:
    app: smtp
  ports:
    - name: smtp
      protocol: TCP
      port: 1025       # SMTP порт для відправки пошти
      targetPort: 1025
    - name: web-ui
      protocol: TCP
      port: 8025       # Web UI для перегляду листів
      targetPort: 8025